[package]
name = "nvim-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
comment = { workspace = true }
mlua = { workspace = true }
nvim-oxi = { workspace = true }
once_cell = { workspace = true }

[workspace]
resolver = "2"
members = ["api", "comment"]

[workspace.dependencies]
# local
api = { path = "./api" }
comment = { path = "./comment" }
# crate
mlua = { version = "0.9.9", features = ["luajit", "module"] }
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10"] }
once_cell = "1.19.0"
